name: Build and Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy Node App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
      - name: run test
        run: npm test
