name: Build and Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and deploy Node App
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node 18
        uses: bahmutov/npm-install@v1
      - name: run test
        run: npm test
